// BeatsEdge AI frontend (Phase 3B) tests. The pure region of BeatsEdge.html (<<AI-UI-BEGIN>> .. <<AI-UI-END>>) is evaluated in a Node `vm`; fixtures come from the REAL shipped engine
// (loadNcaafModel). The requests go to the REAL AI router mounted on an ephemeral local port (deterministic mode, no provider). NO ParlayAPI calls, NO real LLM calls, no React/DOM:
// the JSX components are verified separately in the browser; here we test the store, payload, dedupe, error mapping and view-model they are thin wrappers over.
//   node scripts/test-ai-ui.js
const fs = require('fs'), path = require('path'), http = require('http'), vm = require('vm'); const express = require('express');
const { loadNcaafModel } = require('./lib/loadNcaafModel'); const { validateSelection } = require('../lib/aiService/selection');
const { createStore } = require('../lib/siteTelemetry'); const { createAiRouter } = require('../routes/ai');
let failures = 0; const check = (n, c, d) => { if (c) console.log(`PASS  ${n}`); else { failures++; console.log(`FAIL  ${n}${d ? '  -- ' + d : ''}`); } }; const section = (s) => console.log('\n# ' + s);
const HTML = fs.readFileSync(path.join(__dirname, '..', 'BeatsEdge.html'), 'utf8').replace(/\r\n/g, '\n');
// ---------- load the pure region ----------
const a = HTML.indexOf('// <<AI-UI-BEGIN>>'), b = HTML.indexOf('// <<AI-UI-END>>'); if (a < 0 || b < a) { console.log('FAIL  AI-UI markers missing'); process.exit(1); }
const REGION = HTML.slice(a, b);
const NAMES = ['AI_UI', 'aiBuildSelection', 'aiSelectionKey', 'aiCleanQuestion', 'aiRequestKey', 'aiSubscribe', 'aiEntry', 'aiIsPanelOpen', 'aiSetPanelOpen', 'aiLastQuestion', 'aiSetCurrentSelection', 'aiClearCurrentSelection', 'aiCurrentSelection', 'aiBusyForSelection', 'aiResetStore', 'aiClassifyFailure', 'aiAsk', 'aiViewModel', 'aiPrettyLine', 'aiTelemetryNotices', 'AI_ORIGIN_NOTICE', 'AI_STATE_NOTICE', 'AI_TELEMETRY_NOTICE'];
const sandbox = { console, Date, Math, JSON, Number, String, Array, Object, Map, Set, Promise, RegExp, Error, setTimeout, clearTimeout, AbortController, fetch: undefined };
const ui = vm.runInContext(`(function(){\n${REGION}\n;return { ${NAMES.join(', ')} };})`, vm.createContext(sandbox), { filename: 'BeatsEdge.html#ai-ui' })();
// the two question-chip arrays sit right after the region
const chipSrc = HTML.slice(HTML.indexOf('const AI_PROP_QUESTIONS'), HTML.indexOf('function AskBeatsEdgeResult'));
const chips = vm.runInContext(`(function(){\n${chipSrc}\n;return { AI_PROP_QUESTIONS, AI_SITE_QUESTIONS };})`, vm.createContext({}))();
// ---------- real-engine fixtures ----------
function rng(seed) { let a = seed >>> 0; return () => { a = (a + 0x6D2B79F5) >>> 0; let t = a; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }
const COLS = ['completions', 'passingAttempts', 'passingYards', 'passingTouchdowns', 'interceptions', 'rushingAttempts', 'rushingYards', 'rushingTouchdowns', 'longRushing', 'receptions', 'receivingYards', 'receivingTouchdowns', 'longReception']; const OPPS = ['OSU', 'MICH', 'PSU', 'ALA']; const addDays = (d, n) => new Date(Date.parse(d + 'T12:00:00Z') + n * 864e5).toISOString().slice(0, 10);
const mkGl = (season, games) => { const events = {}; const evs = games.map(g => { events[g.id] = { gameDate: g.date + 'T17:00:00Z', opponent: { abbreviation: g.opp }, atVs: g.away ? '@' : 'vs' }; return { eventId: g.id, stats: COLS.map(n => g.vals[n]) }; }); return { names: COLS, events, seasonTypes: [{ displayName: season + ' Regular Season', categories: [{ events: evs }] }] }; };
function synthGames(seed, pos) { const r = rng(seed), sc = 0.8 + r() * 0.6; const mk = (season, n, d0) => Array.from({ length: n }, (_, i) => { const v = {}; const qb = pos === 'QB', wr = pos === 'WR', rb = pos === 'RB'; v.passingAttempts = qb ? Math.round(24 + r() * 14 * sc) : 0; v.completions = qb ? Math.round(v.passingAttempts * 0.62) : 0; v.passingYards = qb ? Math.round(v.completions * (9 + r() * 4)) : 0; v.passingTouchdowns = qb ? Math.round(1 + r() * 2) : 0; v.interceptions = qb && r() < 0.25 ? 1 : 0; v.rushingAttempts = rb ? Math.round(10 + r() * 12 * sc) : 2; v.rushingYards = Math.round(v.rushingAttempts * (3 + r() * 3)); v.rushingTouchdowns = rb && r() < 0.4 ? 1 : 0; v.longRushing = Math.round(v.rushingYards * 0.4); v.receptions = wr ? Math.round(4 + r() * 5 * sc) : 1; v.receivingYards = Math.round(v.receptions * (9 + r() * 7)); v.receivingTouchdowns = wr && r() < 0.3 ? 1 : 0; v.longReception = Math.round(v.receivingYards * 0.5); return { id: season + 'g' + i + 's' + seed, date: addDays(d0, i * 7), opp: OPPS[(i + seed) % 4], away: i % 2 === 0, vals: v }; }); return [[2025, mk(2025, 13, '2025-08-30')], [2026, mk(2026, 6, '2026-09-05')]]; }
const m = loadNcaafModel();
function playOf(pos, seed, lines) { const rows = m.cfbDedupeRows([].concat(...synthGames(seed, pos).map(([y, g]) => m.cfbParseGamelog(mkGl(y, g), y)))); const L = {}; Object.keys(lines).forEach(k => { L[k] = { prizepicks: [{ line: lines[k], over: 100, under: 100, juice: 0, primary: true, ppType: 'standard', _src: 'parlayapi', eventId: 'ev1', commenceTimeMs: Date.now() + 36e5, setAt: 0 }] }; });
  const { statsByKey, gameLogByKey } = rows.length ? m.cfbWindowsFor(rows, m.nflPosKeys(pos), lines, 'OSU', 2026) : { statsByKey: {}, gameLogByKey: {} }; const per = (k) => { const w = statsByKey[k]; return (w && (w.season.avg || w.recent.avg)) || 0; };
  const props = m.cfbBuildProps(m.nflPosKeys(pos).filter(k => L[k]), statsByKey, L, 'prizepicks', per); props.forEach(p => { p.commenceTimeMs = Date.now() + 36e5; p.eventId = 'ev1'; p.homeTeam = 'Ohio State Buckeyes'; p.awayTeam = 'Michigan Wolverines'; });
  return { id: 'p' + seed, name: 'Test Player', sport: 'ncaaf', role: 'skill', position: pos, team: 'MICH', opponent: 'OSU', oppDef: null, status: 'ACTIVE', statsByKey, gameLogByKey, stats: {}, gameLog: [], props }; }
let modeled; for (let seed = 1; seed < 80 && !modeled; seed++) { const pl = playOf('WR', seed, { recYds: 40.5, receptions: 3.5 }); const pr = pl.props.find(p => p.statKey === 'recYds' && p.direction === 'over'); const edge = pr && pr.modelSupported !== false ? m.calculateEdgeScore(pl, pr) : null; if (edge && !edge.insufficientData && edge.finalGrade && edge.hitRatesSource === 'game_log') modeled = { pl, pr, edge }; }
const nymPl = playOf('RB', 3, { rushTds: 1.5 }); const nymPr = nymPl.props.find(p => p.statKey === 'rushTds'); const nymEdge = m.calculateEdgeScore(nymPl, nymPr);
const emptyPl = playOf('WR', 7, { recYds: 40.5 }); emptyPl.statsByKey = {}; const emptyPr = emptyPl.props[0]; const emptyEdge = m.calculateEdgeScore(emptyPl, emptyPr);
const provOnlyPl = { id: 'prov:nba:x', name: 'Donovan Clingan', sport: 'nba', team: 'POR', status: null, statsByKey: {}, props: [] }; const provOnlyPr = { statKey: 'player_3_pt_attempted', type: '3-PT Attempted', line: 3.5, direction: 'over', book: 'prizepicks', modelSupported: false, eventId: 'ev9', lineSource: 'ParlayAPI - prizepicks' };
// ---------- telemetry fixtures (client-reported) ----------
const src = (o) => Object.assign({ fetchStatus: 'COMPLETE', rawRows: 100, playerPropRows: 90, events: 4, players: 30, mainLineGroups: 80, mainLinesRetained: 78, alternates: 5, altOnlyGroups: 0, providerStandardNotReturned: 0, standardPresentGroups: 0, unmappedMarkets: 2, routedMarketRows: 0, playerIdentityFailures: 0, eventIdentityFailures: 0, ambiguousMainLines: 0, truncatedResponses: 0, providerErrors: 0, duplicates: 0, playerNameSuffixStripped: 0, lineTypes: { standard: 0, demon: 0, goblin: 0, gimme_pick: 0, stat_slice: 0, power_up: 0, unclassified: 0, other: {} } }, o);
const tel = (sport, fetchStatus, sources, extra) => Object.assign({ version: 'beatsedge-site-telemetry/1', generatedAt: new Date().toISOString(), available: true, sport, fetchStatus, fetchMode: 'BROAD', requests: 1, pagesFetched: 1, rowsReceived: 100, failedBooks: [], skippedEmptyBooks: [], bySportSource: Object.fromEntries(Object.entries(sources).map(([k, v]) => [sport + '|' + k, v])) }, extra || {});
function mkStore(clock) { const st = createStore({ now: () => clock.t }); const gen = () => new Date(clock.t).toISOString();
  st.ingest(tel('basketball_nba', 'COMPLETE', { prizepicks: src({ standardPresentGroups: 27, lineTypes: { standard: 27, demon: 0, goblin: 0, gimme_pick: 0, stat_slice: 0, power_up: 0, unclassified: 0, other: {} } }) }, { generatedAt: gen() }), 'a');
  st.ingest(tel('basketball_wnba', 'COMPLETE', { prizepicks: src({ standardPresentGroups: 111, providerStandardNotReturned: 131, altOnlyGroups: 131, lineTypes: { standard: 153, demon: 266, goblin: 127, gimme_pick: 0, stat_slice: 0, power_up: 0, unclassified: 0, other: {} } }) }, { generatedAt: gen() }), 'b');
  st.ingest(tel('americanfootball_nfl', 'TRUNCATED', { bovada: src({ truncatedResponses: 3 }), pick6: src({ ambiguousMainLines: 26 }) }, { generatedAt: gen(), fetchMode: 'SPLIT_BY_MARKET' }), 'c'); return st; }
const serve = (router) => new Promise(res => { const app = express(); app.use(express.json({ limit: '1mb' })); app.use('/api', router); const srv = app.listen(0, '127.0.0.1', () => res({ srv, port: srv.address().port })); });
const sleep = (ms) => new Promise(r => setTimeout(r, ms));

(async () => {
  check('fixtures: a real modeled engine edge, an unmodeled TD edge, an empty-history edge and a provider-only selection exist', !!modeled && !!nymEdge && !!emptyEdge && nymPr.modelSupported !== undefined);
  const clock = { t: Date.parse('2026-10-08T12:00:00Z') }; const store = mkStore(clock); const router = createAiRouter({ store, env: {}, recordedQuery: null }); const { srv, port } = await serve(router); const BASE = 'http://127.0.0.1:' + port; sandbox.fetch = undefined;

  section('1. payload: ONE play, whitelisted, engine values verbatim, never the board');
  const sel = ui.aiBuildSelection(modeled.pl, modeled.pr, modeled.edge);
  { const E = sel.edge, X = modeled.edge;
    check('the engine\'s own projection / edge / probability / grade / Prime / confidence are sent verbatim (never recomputed)', E.projection === X.projection && E.edge === X.edge && E.modelProbPct === X.modelProbPct && E.finalGrade === (X.finalGrade || null) && E.prime === (X.prime === true) && E.confidence === X.confidence && E.totalFactors === X.totalFactors && E.greenCount === X.greenCount, JSON.stringify(E).slice(0, 300));
    check('the real line, direction, book, event and provider identity of the selected prop are sent', sel.prop.line === modeled.pr.line && sel.prop.direction === modeled.pr.direction && sel.prop.statKey === modeled.pr.statKey && sel.prop.book === modeled.pr.book && sel.prop.eventId === 'ev1' && sel.player.name === 'Test Player' && sel.sport === 'ncaaf');
    check('factors are sent as the engine produced them (same count and keys)', E.factors.length === Math.min(24, (X.factors || []).length) && E.factors.every((f, i) => f.key === X.factors[i].key && f.supports === (X.factors[i].supports === true ? true : X.factors[i].supports === false ? false : null)));
    const server = validateSelection(JSON.parse(JSON.stringify(sel))); check('the server accepts it and every engine cross-check passes (nothing dropped)', server.ok && server.integrity.issues.length === 0 && server.integrity.outputsDropped === false, JSON.stringify(server.integrity && server.integrity.issues));
    check('whitelist: no board (player.props), no per-stat windows map, no probSteps / backtest / calibration internals, no other props', !('props' in sel.player) && !('statsByKey' in sel.player) && !JSON.stringify(sel).includes('probSteps') && !JSON.stringify(sel).includes('gameLogByKey') && Object.keys(sel).sort().join() === 'edge,player,prop,sport,windows');
    const big = JSON.parse(JSON.stringify(modeled.pl)); big.props = Array.from({ length: 400 }, (_, i) => Object.assign({}, modeled.pr, { id: 'x' + i, line: i + 0.5 })); const selBig = ui.aiBuildSelection(big, modeled.pr, modeled.edge);
    check('a 400-prop board attached to the player does not change the payload at all', JSON.stringify(selBig) === JSON.stringify(sel) && JSON.stringify({ question: 'q', selection: sel }).length < 12000, String(JSON.stringify(sel).length)); }
  { const e = ui.aiBuildSelection(nymPl, nymPr, nymEdge); check('an unmodeled prop sends its real line and state but NO fabricated model values', e.prop.line === nymPr.line && (e.edge == null || (e.edge.projection == null && e.edge.modelProbPct == null && !e.edge.finalGrade)), JSON.stringify(e.edge));
    const po = ui.aiBuildSelection(provOnlyPl, provOnlyPr, modeled.edge); check('a provider-only prop (modelSupported:false) never carries edge values even if one is passed in', po.edge === null && po.prop.modelSupported === false && po.windows === null);
    check('no player / no prop -> null (nothing to send)', ui.aiBuildSelection(null, nymPr, null) === null && ui.aiBuildSelection(nymPl, null, null) === null);
    const hostile = ui.aiBuildSelection(Object.assign({}, modeled.pl, { name: 'x'.repeat(500) }), Object.assign({}, modeled.pr, { statKey: 'y'.repeat(500), line: 'NaN', odds: Infinity }), null); check('over-long strings are clamped and non-finite numbers become null', hostile.player.name.length <= 60 && hostile.prop.statKey.length <= 90 && hostile.prop.line === null && hostile.prop.odds === null); }

  section('2. selection / request keys');
  { const k = ui.aiSelectionKey(sel); check('selection key is stable for the same selection', k === ui.aiSelectionKey(ui.aiBuildSelection(modeled.pl, modeled.pr, modeled.edge)));
    const alt = (patch) => ui.aiSelectionKey(ui.aiBuildSelection(modeled.pl, Object.assign({}, modeled.pr, patch), modeled.edge)); check('a different line, direction or book is a different selection', alt({ line: modeled.pr.line + 1 }) !== k && alt({ direction: 'under' }) !== k && alt({ book: 'underdog' }) !== k && alt({ statKey: 'receptions' }) !== k);
    check('request key is case / whitespace-insensitive in the question and distinguishes prop vs site and with vs without selection', ui.aiRequestKey('prop', sel, ' Why   is this GOOD? ') === ui.aiRequestKey('prop', sel, 'why is this good?') && ui.aiRequestKey('site', null, 'q') !== ui.aiRequestKey('site', sel, 'q') && ui.aiRequestKey('site', null, 'q') !== ui.aiRequestKey('prop', sel, 'q'));
    check('questions are trimmed and capped', ui.aiCleanQuestion('   a\n\n b  ') === 'a b' && ui.aiCleanQuestion('z'.repeat(1000)).length === ui.AI_UI.MAX_Q && ui.aiCleanQuestion(null) === ''); }

  section('3. aiAsk: dedupe, cache, force, TTL, request shape');
  { ui.aiResetStore(); let n = 0, last = null; const fake = (u, init) => { n++; last = { u, init }; return new Promise(r => setTimeout(() => r({ ok: true, status: 200, json: async () => ({ status: 'DETERMINISTIC_ANSWER', answer: { text: 'ok' } }) }), 30)); };
    let t = 1000; const now = () => t; const args = (o) => Object.assign({ backendUrl: 'http://x.test/', kind: 'prop', question: 'Why is this a good play?', selection: sel, fetchImpl: fake, now }, o || {});
    const p1 = ui.aiAsk(args()), p2 = ui.aiAsk(args({ question: 'why is this a good play?  ' })); check('two identical in-flight questions share ONE request and the same promise', n === 1 && p1 === p2); await p1;
    check('request goes to the explain-prop route as POST JSON with only { question, selection } and no credentials', last.u === 'http://x.test/api/ai/explain-prop' && last.init.method === 'POST' && Object.keys(JSON.parse(last.init.body)).sort().join() === 'question,selection' && Object.keys(last.init.headers).join() === 'Content-Type');
    await ui.aiAsk(args()); check('a fresh answer is reused (no second request) inside the TTL', n === 1);
    await ui.aiAsk(args({ force: true })); check('force bypasses the cache', n === 2); t += ui.AI_UI.TTL_MS + 1; await ui.aiAsk(args()); check('an expired answer is re-requested', n === 3);
    await ui.aiAsk(args({ question: 'What is the biggest risk?' })); check('a different question is a different request', n === 4);
    const sk = ui.aiSelectionKey(sel); const pb = ui.aiAsk(args({ question: 'Explain the grade', force: true })); const busyDuring = ui.aiBusyForSelection(sk); await pb;
    check('busy flag is true while a request for the selection is in flight and clears after completion', busyDuring === true && ui.aiBusyForSelection(sk) === false);
    n = 0; await ui.aiAsk(args({ kind: 'site', selection: null, question: 'How fresh is the data?' })); check('site question goes to the site route with only { question } when nothing is selected', last.u === 'http://x.test/api/ai/site-question' && Object.keys(JSON.parse(last.init.body)).join() === 'question' && n === 1);
    await ui.aiAsk(args({ kind: 'site', selection: sel, question: 'Why is this prop not modeled?' })); check('a selected prop may accompany a site question (one play, same whitelist)', JSON.parse(last.init.body).selection.prop.statKey === sel.prop.statKey); }

  section('4. aiAsk: failure classes (plain language, never raw server text) and retry');
  { ui.aiResetStore(); const mk = (status, body) => () => Promise.resolve({ ok: status >= 200 && status < 300, status, json: async () => body }); const run = async (fi, o) => (await ui.aiAsk(Object.assign({ backendUrl: 'http://x.test', kind: 'prop', question: 'q ' + Math.random(), selection: sel, fetchImpl: fi }, o || {}))).error || {};
    const cases = [[404, null, 'NOT_AVAILABLE', false], [401, null, 'NOT_AUTHORIZED', false], [403, null, 'NOT_AUTHORIZED', false], [429, null, 'RATE_LIMITED', true], [413, null, 'TOO_LARGE', false], [400, { errors: ['bad <script>x</script> field'] }, 'INVALID_REQUEST', false], [500, { error: 'SELECT * FROM secrets' }, 'SERVER_ERROR', true], [503, null, 'SERVER_ERROR', true]];
    for (const [st, body, code, retry] of cases) { const e = await run(mk(st, body)); check(`HTTP ${st} -> ${code}, retryable=${retry}`, e.code === code && e.retryable === retry && typeof e.message === 'string' && e.message.length > 5 && !/SELECT|secrets|<script>/.test(e.message), JSON.stringify(e)); }
    check('a 200 with an unreadable body -> BAD_RESPONSE', (await run(() => Promise.resolve({ ok: true, status: 200, json: async () => { throw new Error('x'); } }))).code === 'BAD_RESPONSE');
    check('a network failure -> UNREACHABLE (retryable)', (e => e.code === 'UNREACHABLE' && e.retryable)(await run(() => Promise.reject(new TypeError('Failed to fetch')))));
    check('a hung request is aborted -> TIMEOUT (retryable)', (e => e.code === 'TIMEOUT' && e.retryable)(await run((u, init) => new Promise((res, rej) => init.signal.addEventListener('abort', () => { const er = new Error('aborted'); er.name = 'AbortError'; rej(er); })), { timeoutMs: 25 })));
    check('no backend URL -> NO_BACKEND without any request; empty question -> EMPTY_QUESTION; missing selection -> NO_SELECTION', (await run(() => { throw new Error('must not be called'); }, { backendUrl: '' })).code === 'NO_BACKEND' && (await run(() => { throw new Error('must not be called'); }, { question: '   ' })).code === 'EMPTY_QUESTION' && (await run(() => { throw new Error('must not be called'); }, { selection: null })).code === 'NO_SELECTION');
    const huge = JSON.parse(JSON.stringify(sel)); huge.prop.flagReason = 'a'.repeat(100); huge.player.name = 'n'.repeat(50); Object.defineProperty(huge, 'toJSON', { value: () => ({ blob: 'x'.repeat(ui.AI_UI.MAX_BODY_CHARS + 10) }) }); check('an oversized payload is refused locally (TOO_LARGE) and never sent', (await run(() => { throw new Error('must not be called'); }, { selection: huge })).code === 'TOO_LARGE');
    let calls = 0; const flaky = () => (++calls === 1 ? Promise.reject(new TypeError('x')) : Promise.resolve({ ok: true, status: 200, json: async () => ({ status: 'DETERMINISTIC_ANSWER', answer: { text: 'fine' } }) })); const A = { backendUrl: 'http://x.test', kind: 'prop', question: 'retry me', selection: sel, fetchImpl: flaky };
    const e1 = await ui.aiAsk(A); const e2 = await ui.aiAsk(A); check('an error is never cached as an answer: asking again retries and succeeds', e1.status === 'error' && e2.status === 'done' && calls === 2);
    const listener = []; const un = ui.aiSubscribe(() => listener.push(1)); ui.aiSetPanelOpen('k', true); check('panel open state is held in the module store and notifies subscribers', ui.aiIsPanelOpen('k') && listener.length === 1); un(); ui.aiSetPanelOpen('k', false); check('unsubscribe stops notifications', listener.length === 1 && !ui.aiIsPanelOpen('k'));
    ui.aiResetStore(); ui.aiSetCurrentSelection(sel); check('current selection is tracked and cleared only by its own key', ui.aiCurrentSelection() === sel && (ui.aiClearCurrentSelection('other'), ui.aiCurrentSelection() === sel) && (ui.aiClearCurrentSelection(ui.aiSelectionKey(sel)), ui.aiCurrentSelection() === null)); }

  section('5. end to end against the REAL router (deterministic mode, no provider)');
  const ask = (kind, question, selection) => ui.aiAsk({ backendUrl: BASE, kind, question, selection, fetchImpl: (u, i) => fetch(u, i), force: true });
  const vmOf = async (kind, q, s) => { const e = await ask(kind, q, s); return { e, vm: e.status === 'done' ? ui.aiViewModel(kind, e.data) : null }; };
  { ui.aiResetStore(); const { e, vm } = await vmOf('prop', 'Why is this a good play?', sel); const d = e.data;
    check('modeled prop: the page gets a 200 answer and the view-model is DETERMINISTIC (no AI provider needed)', e.status === 'done' && !!vm && vm.mode === 'DETERMINISTIC' && vm.aiGenerated === false && vm.hasModel === true, JSON.stringify(e.error || d && d.status));
    const row = (k) => vm.modelRows.filter(r => r.kind === k); const prob = row('probability')[0], conf = row('confluence')[0];
    check('model probability and factor confluence are SEPARATE rows with different kinds', row('probability').length === 1 && row('confluence').length === 1 && prob.label !== conf.label && /%/.test(prob.value) && prob.value.includes(String(modeled.edge.modelProbPct)), JSON.stringify(vm.modelRows));
    check('the shown model values are the engine\'s (projection, edge, grade, probability) verbatim', vm.modelRows.some(r => /^Projection$/i.test(r.label) && r.value.includes(String(modeled.edge.projection))) && vm.modelRows.some(r => /^Grade$/i.test(r.label) && r.value.includes(String(modeled.edge.finalGrade))), JSON.stringify(vm.modelRows));
    check('supporting evidence, opposing/risk evidence and missing info are sections of the view-model', Array.isArray(vm.supporting) && Array.isArray(vm.opposing) && Array.isArray(vm.missing) && vm.supporting.length + vm.opposing.length > 0);
    check('the client-reported origin notice is present and the telemetry notice is present when site data is attached', vm.notices.some(n => n.text === ui.AI_ORIGIN_NOTICE) && vm.notices.some(n => /client-reported/i.test(n.text)));
    check('raw engine codes are never shown as labels', ![].concat(vm.supporting, vm.opposing, vm.missing).some(l => /^(research\.|play\.|model\.|history\.)/.test(l)), JSON.stringify([].concat(vm.supporting, vm.opposing, vm.missing)).slice(0, 300)); }
  { const { vm, e } = await vmOf('prop', 'Why isn\'t this prop modeled?', ui.aiBuildSelection(nymPl, nymPr, nymEdge));
    check('unmodeled prop: no supporting/opposing lists are shown, the state explains why, the real line stays available', e.status === 'done' && vm.hasModel === false && vm.supporting.length === 0 && vm.opposing.length === 0 && vm.notices.some(n => n.text === ui.AI_STATE_NOTICE) && vm.modelRows.length + vm.answerLines.length + (vm.refusal ? 1 : 0) > 0, JSON.stringify(vm).slice(0, 400));
    check('an unmodeled prop never shows a probability, projection or grade row with a value', !vm.modelRows.some(r => (r.kind === 'probability' || /^(Projection|Grade|Edge)$/i.test(r.label)) && /\d/.test(r.value) && !/not|n\/a|unavailable|none/i.test(r.value)), JSON.stringify(vm.modelRows)); }
  { const { vm, e } = await vmOf('prop', 'Why is this a good play?', ui.aiBuildSelection(emptyPl, emptyPr, emptyEdge)); check('empty / insufficient history: no model output is invented (hasModel false, no probability row)', e.status === 'done' && vm.hasModel === false && !vm.modelRows.some(r => r.kind === 'probability' && /\d/.test(r.value) && !/not|unavailable/i.test(r.value))); }
  { const { vm, e } = await vmOf('prop', 'Why is this a good play?', ui.aiBuildSelection(provOnlyPl, provOnlyPr, null)); check('provider-only prop is handled as a real line with no model, never as a refusal crash', e.status === 'done' && vm.hasModel === false && vm.supporting.length === 0); }
  { const tamper = JSON.parse(JSON.stringify(sel)); tamper.edge.modelProbPct = 99.9; tamper.edge.finalGrade = 'A+'; const { vm, e } = await vmOf('prop', 'Explain the probability', tamper);
    check('inconsistent client numbers are flagged to the user as ignored (never repaired by the page or the server)', e.status === 'done' && (vm.ignored.length > 0 || vm.notices.some(n => /failed validation|ignored/i.test(n.text)) || vm.hasModel === false), JSON.stringify(vm.notices)); }

  section('6. site assistant: telemetry is client-reported; missing / stale never looks healthy');
  { const { vm, e } = await vmOf('site', 'Which sports have incomplete data?', null); const txt = vm.answerLines.join(' ');
    check('site answer is deterministic from client-reported telemetry, with the telemetry notice', e.status === 'done' && vm.mode === 'DETERMINISTIC' && vm.notices.some(n => n.text === ui.AI_TELEMETRY_NOTICE) && /NFL/.test(txt) && /INCOMPLETE|truncat/i.test(txt), txt.slice(0, 300));
    check('sports without a current report are shown as unknown / no data, with an explicit "unknown, not confirmed" notice', vm.sports.some(s => s.sport === 'MLB' && !s.reported && s.freshness === 'NO_DATA') && vm.notices.some(n => /no current report: completeness is unknown/i.test(n.text)), JSON.stringify(vm.sports));
    check('the page never marks a sport healthy: every reported sport carries its freshness and every unreported sport is NO_DATA', vm.sports.length >= 5 && vm.sports.every(s => s.reported ? ['FRESH', 'STALE', 'EXPIRED'].includes(s.freshness) : s.freshness === 'NO_DATA')); }
  { const r = await vmOf('site', 'Are PrizePicks Standard lines available?', null); check('PrizePicks Standard question: answered from telemetry with the WNBA Standard gap named', r.e.status === 'done' && /Standard/i.test(r.vm.answerLines.join(' ')) && /WNBA/.test(r.vm.answerLines.join(' ')), r.vm.answerLines.join(' ').slice(0, 300)); }
  { const r = await vmOf('site', 'Why is a player missing from the board?', null); const t = r.vm.answerLines.join(' '); check('missing-player question: BeatsEdge does NOT claim to know which player is missing (aggregate telemetry carries counts, not names)', r.e.status === 'done' && /cannot|can't|not (carry|include|name|know)|no player names|counts, not/i.test(t) && !/Test Player|Clingan/.test(t), t.slice(0, 300)); }
  { const r = await vmOf('site', 'Any provider errors or truncation?', null); check('errors & truncation question surfaces the NFL truncation', /truncat/i.test(r.vm.answerLines.join(' ')), r.vm.answerLines.join(' ').slice(0, 300)); }
  { clock.t += 3 * 24 * 3600e3; const r = await vmOf('site', 'How fresh is the data?', null);
    check('STALE / EXPIRED telemetry is never shown as healthy: sports are not FRESH and a warning says completeness is unknown', r.e.status === 'done' && r.vm.sports.filter(s => s.reported).every(s => s.freshness !== 'FRESH') && r.vm.notices.some(n => n.level === 'warn' && /stale|expired|unknown|no current telemetry/i.test(n.text)), JSON.stringify(r.vm.notices) + JSON.stringify(r.vm.sports)); clock.t -= 3 * 24 * 3600e3; }
  { const empty = createStore({ now: () => clock.t }); const { srv: s2, port: p2 } = await serve(createAiRouter({ store: empty, env: {}, recordedQuery: null })); const e = await ui.aiAsk({ backendUrl: 'http://127.0.0.1:' + p2, kind: 'site', question: 'Which sports have incomplete data?', fetchImpl: (u, i) => fetch(u, i), force: true }); const vm = ui.aiViewModel('site', e.data);
    check('no telemetry at all: the UI says nothing can be confirmed healthy and lists no sport as reported', e.status === 'done' && vm.sports.every(s => !s.reported) && vm.notices.some(n => n.level === 'warn' && /nothing here can be confirmed healthy/.test(n.text))); s2.close(); }
  { const n = ui.aiTelemetryNotices('NO_DATA', false, []); const st = ui.aiTelemetryNotices('STALE', true, ['STALE_REPORT']); const fr = ui.aiTelemetryNotices('FRESH', true, ['PROVIDER_ERRORS']);
    check('telemetry notice helper: NO_DATA and STALE warn; flags are labelled "Client-reported"; the base notice is always last', n[0].level === 'warn' && st[0].level === 'warn' && fr.some(x => /^Client-reported: provider errors/.test(x.text)) && fr[fr.length - 1].text === ui.AI_TELEMETRY_NOTICE)}
  { const r = await vmOf('site', 'Why is this prop not modeled?', ui.aiBuildSelection(nymPl, nymPr, nymEdge)); check('"why isn\'t this prop modeled" through the site assistant with a selected prop answers from the prop\'s own state', r.e.status === 'done' && r.vm.answerLines.join(' ').length > 20, JSON.stringify(r.e.error || r.vm.status)); }

  section('7. question chips');
  { const all = [].concat(chips.AI_PROP_QUESTIONS, chips.AI_SITE_QUESTIONS); check('every chip is a [question, label] pair within the question cap', all.every(c => Array.isArray(c) && c.length === 2 && c[0].length > 5 && c[0].length <= ui.AI_UI.MAX_Q && c[1].length > 3));
    check('the required topics are covered: Standard lines, incomplete sports, provider-only props, errors/truncation, freshness, a missing player, why not modeled', /Standard/.test(JSON.stringify(chips.AI_SITE_QUESTIONS)) && /ncomplete/.test(JSON.stringify(chips.AI_SITE_QUESTIONS)) && /rovider-only/.test(JSON.stringify(chips.AI_SITE_QUESTIONS)) && /truncation/.test(JSON.stringify(chips.AI_SITE_QUESTIONS)) && /fresh/.test(JSON.stringify(chips.AI_SITE_QUESTIONS)) && /missing/.test(JSON.stringify(chips.AI_SITE_QUESTIONS)) && /modeled/.test(JSON.stringify(chips.AI_PROP_QUESTIONS)));
    let bad = []; for (const c of chips.AI_SITE_QUESTIONS) { const e = await ask('site', c[0], null); if (e.status !== 'done' || !ui.aiViewModel('site', e.data).answerLines.length) bad.push(c[1]); } check('every site chip gets a deterministic answer from the real backend', bad.length === 0, bad.join());
    bad = []; for (const c of chips.AI_PROP_QUESTIONS) { const e = await ask('prop', c[0], sel); if (e.status !== 'done') bad.push(c[1]); } check('every prop chip is accepted by the real backend for a modeled prop', bad.length === 0, bad.join()); }

  section('8. source pins (page wiring)');
  { const region = REGION;
    check('the pure region never calls the engine or computes model values (no calculateEdgeScore, no Math.round / toFixed)', !/calculateEdgeScore|Math\.round|toFixed|Math\.floor/.test(region));
    check('the page talks only to the two AI routes; no vendor, key, provider env name, lib/ai reference or ParlayAPI call inside the AI UI', (() => { const routes = [...new Set(region.match(/\/api\/ai\/[a-z-]+/g) || [])].sort(); return routes.join() === '/api/ai/explain-prop,/api/ai/site-question' && !/BEATSEDGE_AI_|lib\/ai|api\.openai|api\.anthropic|sk-ant|parlay/i.test(region); })());
    const compSrc = HTML.slice(HTML.indexOf('const AI_PROP_QUESTIONS'), HTML.indexOf('const AI_PROP_QUESTIONS') + 20000);
    check('the prop panel is mounted exactly once, inside ErrorBoundary, with the engine edge for the SAME cardProp', (HTML.match(/<AskBeatsEdgePanel /g) || []).length === 1 && /const _askEdge = cardProp\.modelSupported === false \? null : calculateEdgeScore\(player, cardProp\);/.test(HTML) && /<ErrorBoundary name="AskBeatsEdge" resetKey=\{cardProp\.id\}><AskBeatsEdgePanel player=\{player\} prop=\{cardProp\} edge=\{_askEdge\}/.test(HTML));
    check('the site assistant is mounted once, inside ErrorBoundary, using the configured backend URL', (HTML.match(/<AskBeatsEdgeAssistant /g) || []).length === 1 && /<ErrorBoundary name="AskBeatsEdgeAssistant" resetKey="assistant"><AskBeatsEdgeAssistant backendUrl=\{backendUrl\} \/><\/ErrorBoundary>/.test(HTML));
    check('components are top-level (declared outside App) so they survive re-renders; panel state lives in the module store', /\n        function AskBeatsEdgePanel\(/.test(HTML) && /\n        function AskBeatsEdgeAssistant\(/.test(HTML) && HTML.indexOf('function AskBeatsEdgePanel(') < HTML.indexOf('const App = ') + 1e9 && HTML.indexOf('function AskBeatsEdgePanel(') < HTML.search(/function App\(|const App = /));
    check('controls are real, labelled and disabled while a request is in flight (no duplicate submission)', /disabled=\{busy/.test(compSrc) && /aria-expanded/.test(compSrc) && /aria-live/.test(compSrc) && /role="dialog"/.test(compSrc) && /Escape/.test(compSrc));
    check('an unavailable or failing AI never hides the prop: the panel is collapsed by default and failures render inline with a retry', /ask-be-retry/.test(compSrc) && /aiClassifyFailure|\.error\b/.test(compSrc)); }

  srv.close(); console.log(failures ? `\n${failures} FAILURE(S)` : '\nAll AI UI checks passed.'); process.exit(failures ? 1 : 0);
})().catch(e => { console.error(e); process.exit(2); });
