// Pure schema/migration logic for the NFL tables — no `better-sqlite3`
// import here on purpose. Both lib/nflDb.js (the live server, via
// better-sqlite3) and scripts/ingest-nflverse-stats.js (via node:sqlite's
// DatabaseSync, to dodge a native crash — see that script's header comment)
// call this against their own db handle. Either handle works: both expose
// the same sync .exec()/.prepare().all() surface.
function runNflMigrations(db) {
  // nfl_defense_by_position is a fully-derived cache (rebuilt every
  // recompute from nfl_player_game_stats), so a shape change is safe to
  // handle by dropping and recreating it rather than migrating column-by-
  // column — no real information lives here that isn't already in the raw
  // table. Only drop it if it's still the OLD shape (missing season_year),
  // so this is a no-op after the first run on an already-migrated database.
  try {
    const cols = db.prepare(`PRAGMA table_info(nfl_defense_by_position)`).all().map(c => c.name);
    if (cols.length && !cols.includes('season_year')) {
      db.exec(`DROP TABLE nfl_defense_by_position`);
    }
  } catch (e) { /* table doesn't exist yet — CREATE below handles it */ }

  db.exec(`
  CREATE TABLE IF NOT EXISTS nfl_player_game_stats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    season INTEGER NOT NULL,
    week INTEGER NOT NULL,
    season_type TEXT NOT NULL,          -- 'REG' | 'POST'
    game_date TEXT,                     -- derived, approximate (see ingest notes)
    player_id TEXT,
    player_name TEXT NOT NULL,
    position TEXT NOT NULL,             -- QB | RB | WR | TE (only prop-relevant positions ingested)
    team TEXT NOT NULL,
    opponent TEXT NOT NULL,
    passing_yards REAL DEFAULT 0,
    passing_tds REAL DEFAULT 0,
    interceptions REAL DEFAULT 0,
    rushing_yards REAL DEFAULT 0,
    rushing_tds REAL DEFAULT 0,
    receptions REAL DEFAULT 0,
    targets REAL DEFAULT 0,
    receiving_yards REAL DEFAULT 0,
    receiving_tds REAL DEFAULT 0,
    fantasy_points_ppr REAL DEFAULT 0,
    source TEXT DEFAULT 'nflverse-seed'
  );
  CREATE UNIQUE INDEX IF NOT EXISTS idx_nfl_stats_unique ON nfl_player_game_stats(season, week, season_type, player_id);
  CREATE INDEX IF NOT EXISTS idx_nfl_stats_opponent ON nfl_player_game_stats(opponent, position, season, week);

  -- Precomputed rollups, same pattern as NBA's defense_by_position. Column
  -- list expanded (opportunity volume + split-by-type TDs) as part of the
  -- NFL DvP live-wiring pass.
  -- window_type: 'L3' | 'L5' | 'L10' (rolling last-N games, may cross a
  -- season boundary — that's the point of a rolling window) | 'season'
  -- (current season ONLY, never blended with any other season) |
  -- 'multiseason' (last 3 complete seasons, a stable baseline for when
  -- 'season' is too thin to stand on its own — see MIN_GAMES_FOR_CURRENT_SEASON
  -- in nflDvpEngine.js). season_year is populated only for window_type='season'
  -- so a caller always knows exactly which season a "current" row means.
  CREATE TABLE IF NOT EXISTS nfl_defense_by_position (
    team TEXT NOT NULL,
    position TEXT NOT NULL,             -- QB | RB | WR | TE
    window_type TEXT NOT NULL,          -- 'L3' | 'L5' | 'L10' | 'season' | 'multiseason'
    season_year INTEGER,                -- non-null only when window_type='season'
    pass_attempts_allowed REAL,
    completions_allowed REAL,
    passing_yards_allowed REAL,
    passing_tds_allowed REAL,
    rush_attempts_allowed REAL,
    rushing_yards_allowed REAL,
    rushing_tds_allowed REAL,
    targets_allowed REAL,
    receptions_allowed REAL,
    receiving_yards_allowed REAL,
    receiving_tds_allowed REAL,
    fantasy_points_allowed REAL,
    rank INTEGER,                       -- ranked by fantasy_points_allowed within this window_type: 1 = fewest allowed (toughest defense)
    games_sampled INTEGER,
    updated_at TEXT DEFAULT (datetime('now')),
    PRIMARY KEY (team, position, window_type)
  );

  -- Raw per-team-per-game defensive interception facts — the source rows
  -- for nfl_defense_interceptions below. Kept separate from
  -- nfl_player_game_stats (which only carries QB/RB/WR/TE, the offensive
  -- skill positions this app grades props on) because interceptions are
  -- generated by defensive players (LB/CB/SAF/DE/DT/...) this app has no
  -- other reason to ingest per-player.
  CREATE TABLE IF NOT EXISTS nfl_team_defense_game (
    season INTEGER NOT NULL,
    week INTEGER NOT NULL,
    season_type TEXT NOT NULL,
    team TEXT NOT NULL,                 -- the defense
    opponent TEXT NOT NULL,
    interceptions_generated REAL DEFAULT 0,
    pass_attempts_faced REAL DEFAULT 0,  -- denominator for interception rate
    PRIMARY KEY (season, week, season_type, team)
  );

  -- Same window set as nfl_defense_by_position, computed from
  -- nfl_team_defense_game. Terminology matches what these numbers actually
  -- mean (generated BY this defense, not "allowed") per explicit instruction.
  CREATE TABLE IF NOT EXISTS nfl_defense_interceptions (
    team TEXT NOT NULL,
    window_type TEXT NOT NULL,          -- 'L3' | 'L5' | 'L10' | 'season' | 'multiseason'
    season_year INTEGER,
    interceptions_generated REAL,       -- total count across the window's games
    interceptions_per_game REAL,
    interception_rate REAL,             -- interceptions_generated / pass_attempts_faced
    pass_attempts_faced REAL,
    games_sampled INTEGER,
    updated_at TEXT DEFAULT (datetime('now')),
    PRIMARY KEY (team, window_type)
  );
  `);

  // Three fields nflverse's raw feed always carried but this app never
  // stored (pass attempts allowed/completions allowed/rush attempts
  // allowed need the player's own attempts/completions/carries on the SAME
  // row to aggregate from) — added via ALTER so the already-ingested
  // 2022-2024 rows are kept, not dropped. Guarded so re-running this on an
  // already-migrated DB is a no-op.
  const existingCols = new Set(db.prepare(`PRAGMA table_info(nfl_player_game_stats)`).all().map(c => c.name));
  [
    ['pass_attempts', 'REAL DEFAULT 0'],
    ['completions', 'REAL DEFAULT 0'],
    ['rush_attempts', 'REAL DEFAULT 0']
  ].forEach(([col, def]) => {
    if (!existingCols.has(col)) db.exec(`ALTER TABLE nfl_player_game_stats ADD COLUMN ${col} ${def}`);
  });
}

module.exports = { runNflMigrations };
